version: "3.8"

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG} # аргумент .env для подключения xdebug
#    environment:
#      PHP_IDE_CONFIG: "serverName=Docker"
#    user: "www-data"
    volumes:
      - ./../:/var/www/
#    ports:
#      - ${NGINX_HOST_HTTP_PORT}:8080

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm